source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'yoyoba' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-mobad', :path => '../node_modules/react-native-mobad'

  pod 'react-native-bloom-ad', :path => '../node_modules/react-native-bloom-ad'

  target 'yoyobaTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'yoyoba-tvOS' do
  # Pods for yoyoba-tvOS

  target 'yoyoba-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
